POST http://localhost:4200/api/user/register HTTP/1.1

{    
   "name": "maciek",
   "email":"maciek@email.pl",
   "password":"ZAQ!xsw2"
}


###
GET http://localhost:4200/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwucGwiLCJpZCI6MSwiaWF0IjoxNjg2ODIxOTQwLCJleHAiOjE2ODY5MDgzNDB9.F4_pz4McMO_-K684AWB0pOjoRiWNq2WIneK8VTKfT48


###
POST http://localhost:4200/api/user/login HTTP/1.1

{ 
  "email":"maciek@email.pl",
  "password":"ZAQ!xsw2"
}

###
GET http://localhost:4200/api/user HTTP/1.1