GET http://localhost:4200/api/filters/metadata/1

### dzialaja te 2 gety
GET http://localhost:4200/api/photos/user/edf

###
PATCH http://localhost:4200/api/filters

{
    "id": 1,
    "method": "reformat",
    "rotate": 0,
    "width": 100,
    "height": 100,
    "left": 0,
    "right": 0,
    "newFormat": "png",
    "r": 0,
    "g": 0,
    "b": 0
}

###
GET http://localhost:4200/api/getfile/5


