# POST - add a new photo

POST http://localhost:4200/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="file"; filename="wer.jpeg"
Content-Type: image/jpeg

< ./wer.jpeg

--Boundary
Content-Disposition: form-data; name="album"
Content-Type: text/plain

testuser001
--Boundary--