# Get all photos

GET http://localhost:3000/api/photos HTTP/1.1

### GET - pobierz jeden element wg id
GET http://localhost:3000/api/photos/2 HTTP/1.1

### DELETE - usuń wg id
DELETE http://localhost:3000/api/photos/1 HTTP/1.1
